# Generated by Django 5.2 on 2025-04-25 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_sheet_sub_topic_alter_sheet_topic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sheet",
            name="parent_sheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="main.sheet",
            ),
        ),
        migrations.AddField(
            model_name="sheet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sheet",
            name="version_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="sheet",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="sheet",
            name="include_answer_key",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="sheet",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
